version: "3.3"
services:

   app:
      build: ./MedicalAssistant/
      ports:
      - "5000:5000"
      volumes:
      - ./MedicalAssistant/static:/static
      image: app_container
      
   
   model_text:
      build: ./MedicalAssistant/model_qa
      ports:
      - "6000:5000"
      image: model_text_container
      
   model_skin:
      build: ./MedicalAssistant/model_skin
      ports:
      - "7000:5000"
      image: model_skin_container
